name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.8'
      - name: Install dependencies
        run: go get .
      - name: Test with the Go CLI
        run: go test -cover -v ./...
      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: '1.21.8'
